### PR TITLE
Added Rubocop

### PR DESCRIPTION
**Pull request by valeserber**
## Added Rubocop

**Summary**
Installed Rubocop and fixed the errors that Rubocop showed.

**Test plan**
Run *bundle exec rubocop app -R* in the console and see that there aren't any errors

**Trello card**
https://trello.com/c/w5jAVpSu/8-configurar-rubocop

### CODE REVIEW

**Comment by gastonponti** [comment]
:+1: merge the other pr (authentication) first

**Comment by gastonponti** [comment]
You'll need to fix the 'store_location' method in application_controller.rb

**Comment by valeserber** [comment]
@gastonponti fixed

**Comment by gastonponti** [comment]
:+1:

**Pull request merged**
